language: node_js
node_js:
  - "node"
branches:
  only:
    - master
script: ./deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: swagger-ui/dist
  on:
    branch: master
notifications:
  email: false
